name: Check for new shows
on:
  push:
  schedule:
    - cron: "0 4 * * *"
jobs:
  run-check-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install
      - uses: actions/github-script@v5
        env:
          ABOSS_URL: ${{ secrets.ABOSS_URL }}
          ABOSS_TOKEN: ${{ secrets.ABOSS_TOKEN }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          NETLIFY_HOOK: ${{ secrets.NETLIFY_HOOK }}
        with:
          script: require('./check-for-new-shows.js');