name: Check for new shows
on:
  push:
  schedule:
    - cron: "0 4 * * *"
jobs:
  run-check-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-deps-v1
          restore-keys: |
            ${{ runner.os }}-deps-
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install @upstash/redis node-fetch object-hash
      - uses: actions/github-script@v5
        env:
          ABOSS_URL: ${{ secrets.ABOSS_URL }}
          ABOSS_TOKEN: ${{ secrets.ABOSS_TOKEN }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          NETLIFY_HOOK: ${{ secrets.NETLIFY_HOOK }}
        with:
          script: require('./check-for-new-shows.js');